export interface Project {
  slug: string;
  title: string;
  category: string;
  year: string;
  previewImage: string;
  buttonText: string;
  previewLink: string;
  overview: string;
  client: string;
  service: string;
  challengeTitle: string;
  challengeText: string;
  solutionTitle: string;
  solutionText: string;
  gallery: string[];
}

export const projects: Project[] = [
  {
    slug: "velocity",
    title: "Velocity Platform",
    category: "Software Engineering",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/f7oyi2aIDMI2iUNKjywMMhvxJw.jpg",
    buttonText: "Source Code",
    previewLink: "https://github.com/mugisham37",
    overview: "Microservices-based business management platform with Next.js 15, NestJS, and React Native serving 10,000+ users — with GraphQL APIs, multi-database architecture, and Kubernetes deployments.",
    client: "Velocity",
    service: "Full-Stack Development, DevOps",
    challengeTitle: "Challenge",
    challengeText: "Building a unified platform for diverse business operations — inventory, HR, finance, and CRM — required a scalable, fault-tolerant microservices architecture that could handle concurrent usage at scale while maintaining GDPR compliance.",
    solutionTitle: "Solution",
    solutionText: "Designed Apollo Federation-based GraphQL APIs across independent NestJS services, with Redis caching, PostgreSQL clustering, and Kubernetes orchestration for zero-downtime deployments. Integrated OAuth2, SAML, RBAC, and 2FA for enterprise-grade security.",
    gallery: [
      "https://framerusercontent.com/images/0YXh0bkFGKxtQXqwZ4FknVxQ.jpg",
      "https://framerusercontent.com/images/vRcX31A0p0E7RIv4uPKIu2atBg.jpg",
      "https://framerusercontent.com/images/gqLJuWPk1O9hiVXDLjNdgetfJo4.jpg",
    ],
  },
  {
    slug: "drive-master",
    title: "Drive Master",
    category: "Software Engineering",
    year: "'23",
    previewImage: "https://framerusercontent.com/images/rSYCc9NuZxZZzbjxPH3muXhXZvg.jpg",
    buttonText: "Source Code",
    previewLink: "https://github.com/mugisham37",
    overview: "Adaptive learning platform with 11+ microservices across Go, Node.js, and Python — featuring an ML-powered personalization engine with 87% accuracy for learner gap detection, and offline-first mobile and web apps.",
    client: "Drive Master",
    service: "Full-Stack Development, ML Engineering",
    challengeTitle: "Challenge",
    challengeText: "Building an offline-first, adaptive learning system that could personalize content for each learner's unique gaps — deployable across mobile, web, and low-connectivity environments simultaneously, with a microservices backend spanning three languages.",
    solutionTitle: "Solution",
    solutionText: "Built a PyTorch-based ML engine for learner gap detection, offline-first Flutter and Next.js apps with SQLite sync, and a Kubernetes + Istio + ArgoCD infrastructure monitored via Prometheus and Grafana. 11+ microservices coordinated via gRPC and message queues.",
    gallery: [
      "https://framerusercontent.com/images/AaYLA1yhidzg7tDVCJPBFkbWU.jpg",
      "https://framerusercontent.com/images/YiPP5eVO00N0ZsYiybYqyphIk.jpg",
      "https://framerusercontent.com/images/3gJReDa5BpWEsSKGHwx3Ph0xc.jpg",
    ],
  },
  {
    slug: "elev8-rwanda",
    title: "Elev8 Rwanda",
    category: "Software Engineering",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/0JqN0I0NxBZBY7Ro4fimcjlr0g.jpg",
    buttonText: "Live Website",
    previewLink: "https://elev8rwanda.com",
    overview: "Multilingual enterprise website built with Next.js 14, supporting English, French, and Arabic with dynamic locale routing, RTL layout support, and Sanity CMS integration — serving 5,000+ monthly visitors.",
    client: "Elev8 Rwanda",
    service: "Full-Stack Development, Web Design",
    challengeTitle: "Challenge",
    challengeText: "Creating a seamless trilingual experience — including RTL Arabic layout — while maintaining consistent performance, brand integrity, and a content management system non-technical staff could use without developer support.",
    solutionTitle: "Solution",
    solutionText: "Implemented Next.js 14 i18n routing with custom RTL layouts, Sanity headless CMS with typed schemas reducing content update time by 80%, 50+ Radix UI components, SSR optimization, and image compression — achieving 95+ Lighthouse scores and 40% SEO improvement.",
    gallery: [
      "https://framerusercontent.com/images/uMFQ2z0nFgi8cj9lwtdIVrKcH3U.jpg",
      "https://framerusercontent.com/images/K6o9sUaC2WbrBFFNg6dLy2aJf8c.jpg",
      "https://framerusercontent.com/images/0I7SxunxLIshSwCrvVdGTufSqzk.jpg",
    ],
  },
  {
    slug: "nexus",
    title: "Nexus Design System",
    category: "Web Design",
    year: "'25",
    previewImage: "https://framerusercontent.com/images/jcmBjluMDrVi5NXW9ZtGVQOrJpI.jpg",
    buttonText: "View on Figma",
    previewLink: "https://www.figma.com/@mugisham",
    overview: "A comprehensive design system and component library for modern web applications — built in Figma with a focus on accessibility, scalability, and visual consistency across product types.",
    client: "Personal Project",
    service: "Web Design, UI/UX",
    challengeTitle: "Challenge",
    challengeText: "Creating a design system flexible enough to serve diverse product types — from dashboards to marketing sites — while keeping it coherent, well-documented, and immediately usable by developers without a lengthy handoff process.",
    solutionTitle: "Solution",
    solutionText: "Built atomic design principles into a Figma library with 200+ components, semantic color tokens for light/dark modes, responsive grid templates, and interactive prototypes for every component state — paired with a living documentation site.",
    gallery: [
      "https://framerusercontent.com/images/axJGoIx7xyzBOE4ZzKU31lZYJsE.jpg",
      "https://framerusercontent.com/images/GV0tzcN1ITMr4gDpFvVDvLKwNqY.jpg",
      "https://framerusercontent.com/images/uumOeVdewZj5oX4u69tpJS6EQ.jpg",
    ],
  },
  {
    slug: "momentum-studio",
    title: "Momentum Studio",
    category: "Web Design",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/vbCFzEQhFbjMnzTyy0HJBzCwlIY.jpg",
    buttonText: "View on Figma",
    previewLink: "https://www.figma.com/@mugisham",
    overview: "A portfolio and booking website for a creative production studio, designed for high visual impact with a minimal, editorial feel — letting the work speak for itself.",
    client: "Momentum Creative",
    service: "Web Design",
    challengeTitle: "Challenge",
    challengeText: "Balancing the studio's need for a bold, expressive visual identity with fast loading times and a clean UX that put their portfolio work at the forefront without visual clutter or distraction.",
    solutionTitle: "Solution",
    solutionText: "Designed a full-bleed editorial layout in Figma with a dark/light mode system, smooth scroll interactions, and a streamlined booking flow — optimized for web performance with minimal JS and lazy-loaded media.",
    gallery: [
      "https://framerusercontent.com/images/X3PjTLiK3d1YoVxfiOwUhlGvx8.jpg",
      "https://framerusercontent.com/images/Kfc7YrMQRL7DaiQuGMSGwB2dIk.jpg",
      "https://framerusercontent.com/images/8K7i1HVZKZeTqqK56wJIvLHCFh0.jpg",
      "https://framerusercontent.com/images/qOI5dXCoWkxXMyJ3q0eR5OoF7dw.jpg",
    ],
  },
  {
    slug: "kinetics",
    title: "Kinetics Brand Reel",
    category: "Motion Graphics",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/DizHARMZJvhRrgRzoshkdmIiL28.jpg",
    buttonText: "Watch Reel",
    previewLink: "https://www.youtube.com/@mugisham37",
    overview: "A high-energy motion graphics campaign reel for a sportswear brand launch — combining kinetic typography, 3D elements, and dynamic transitions to capture the brand's athletic identity.",
    client: "Kinetics Apparel",
    service: "Motion Graphics, Animation",
    challengeTitle: "Challenge",
    challengeText: "Translating a brand's high-performance, athletic identity into 60 seconds of motion content that could run across social media, digital billboards, and broadcast simultaneously — each with different aspect ratios and timing requirements.",
    solutionTitle: "Solution",
    solutionText: "Created a modular motion system in After Effects with custom easing curves, particle trail effects, and synchronized audio design. Built the timeline as a set of reusable modules exportable in multiple aspect ratios for all platforms without re-animating.",
    gallery: [
      "https://framerusercontent.com/images/YXqXVZ8oiZdT2LUIKKnsiHVZaXQ.jpg",
      "https://framerusercontent.com/images/0U1st2R4vX6hOJmWeDlwAOxledU.jpg",
      "https://framerusercontent.com/images/MQBYmeEKfAR5PvR5xvJLUJo8.jpg",
      "https://framerusercontent.com/images/nPNs6HN2OweGhXRLO3SK11JXwgA.jpg",
      "https://framerusercontent.com/images/H6naCCCwp3wMtmvjaX9wdG5yOXI.jpg",
    ],
  },
  {
    slug: "luminary",
    title: "Luminary Motion Pack",
    category: "Motion Graphics",
    year: "'23",
    previewImage: "https://framerusercontent.com/images/KwOIBd14OUFE2m4G8YX20blRVE.jpg",
    buttonText: "Watch Reel",
    previewLink: "https://www.youtube.com/@mugisham37",
    overview: "A branded motion graphics package for a documentary production company — lower thirds, transitions, title cards, and animated logo reveals crafted to feel cinematic and premium.",
    client: "Luminary Studios",
    service: "Motion Graphics",
    challengeTitle: "Challenge",
    challengeText: "Developing a motion identity that felt cinematic and premium without overshadowing the documentary content it accompanied — the graphics had to serve the story, not compete with it.",
    solutionTitle: "Solution",
    solutionText: "Designed a restrained motion system with film-inspired color grading, subtle kinetic typography, and fluid transitions — fully templatized in After Effects with editable text layers and color controls so the client's internal team could adapt it without a designer.",
    gallery: [
      "https://framerusercontent.com/images/jVqCkEkTcLzubjAcnZqxgrMzgs.jpg",
      "https://framerusercontent.com/images/EZ6FyXr46GicQeSvRsAWhf9kRWg.jpg",
      "https://framerusercontent.com/images/pbL0mUDwLh1Y4SW7OSYQiGZiVqk.jpg",
      "https://framerusercontent.com/images/zACxCnLqLw2YFiC2M3CyuUYm7hI.jpg",
    ],
  },
  {
    slug: "afterglow",
    title: "Afterglow VFX",
    category: "VFX",
    year: "'23",
    previewImage: "https://framerusercontent.com/images/fH1YoRgLBMvw05yvsusCgLYGY.png",
    buttonText: "Watch Breakdown",
    previewLink: "https://www.youtube.com/@mugisham37",
    overview: "Visual effects work for an independent short film — sky replacements, particle effects, light wraps, and full scene color grading to achieve a convincing near-future urban aesthetic on a limited budget.",
    client: "Short Film — \"Afterglow\"",
    service: "VFX Compositing",
    challengeTitle: "Challenge",
    challengeText: "Creating a convincing near-future urban world within the constraints of an independent short film, where practical sets had to be digitally extended and enhanced in post — with no second-unit photography days available.",
    solutionTitle: "Solution",
    solutionText: "Used photogrammetry-based matte painting, particle simulations in After Effects, and node-based compositing to seamlessly blend practical footage with digital environments. A single shooting day was extended into five distinct visual environments in post.",
    gallery: [
      "https://framerusercontent.com/images/Pr4YBlH2I18xrIiYVSGIfWCDU.jpg",
      "https://framerusercontent.com/images/tNDsQjkK9a1W4ZlHHy6Q3bAVGHI.jpg",
      "https://framerusercontent.com/images/dSCQ0YO0t5XkW5AsGpr7VIJL3I.jpg",
      "https://framerusercontent.com/images/UAZltr2XP2JeEg1bGpysyUuCiE.jpg",
      "https://framerusercontent.com/images/kNXyPDtLG8v02FAGmr45easj98.jpg",
    ],
  },
  {
    slug: "solaris",
    title: "Solaris Compositing",
    category: "VFX",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/CqkOPjD1SlEzLYIoZGMdGUT5w.jpg",
    buttonText: "Watch Reel",
    previewLink: "https://www.youtube.com/@mugisham37",
    overview: "Full compositing and color pipeline for a commercial campaign — particle atmospherics, light simulations, and multi-layer compositing across 12 hero shots, delivered with brand-consistent color across the entire campaign.",
    client: "Solaris Media",
    service: "VFX, Color Grading",
    challengeTitle: "Challenge",
    challengeText: "Delivering photorealistic VFX across 12 diverse hero shots — each with unique lighting conditions, locations, and camera moves — while maintaining strict color consistency across the entire campaign for broadcast delivery.",
    solutionTitle: "Solution",
    solutionText: "Established a node-based compositing pipeline with shared color LUTs applied at the project level, modular particle systems reused across shots with per-shot adjustments, and a supervised color grade in DaVinci Resolve for brand-consistent final delivery.",
    gallery: [
      "https://framerusercontent.com/images/wCkQr2zDR08Vy6xX8mS1lsvZE.jpg",
      "https://framerusercontent.com/images/XPFByP9h7E7xgKp3aHf0zuyxzQ.jpg",
      "https://framerusercontent.com/images/uDETrNAAbgCzHqNUpnzGNAiyP4.jpg",
      "https://framerusercontent.com/images/5IOKMsZGqZH5baVORJfb94L6KM4.jpg",
    ],
  },
  {
    slug: "terravox",
    title: "Terravox 3D",
    category: "3D Design",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/RaSrkE8nM37bsXSaA4VshcSjg2c.jpg",
    buttonText: "View on ArtStation",
    previewLink: "https://www.artstation.com/mugishamoses",
    overview: "High-fidelity 3D product visualization for a hardware tech startup's crowdfunding campaign — exploded views, material studies, and an animated hero turntable, all produced before physical prototypes existed.",
    client: "Terravox Tech",
    service: "3D Design, Product Visualization",
    challengeTitle: "Challenge",
    challengeText: "Creating photorealistic 3D renders of a prototype product — before physical samples existed — accurate enough for investor presentations and a crowdfunding campaign where backers needed to trust the product was real.",
    solutionTitle: "Solution",
    solutionText: "Modeled the product in Blender from engineering CAD files, applied physically-based materials with HDR studio lighting setups, and produced a series of hero stills, an exploded-view animation, and a 10-second turntable for the campaign landing page.",
    gallery: [
      "https://framerusercontent.com/images/zBOcZQv01mdr4RGpBfYqh318Q.jpg",
      "https://framerusercontent.com/images/Bkgn6YRamshLbKA9cKIVgLFitw.jpg",
      "https://framerusercontent.com/images/QBQa3mIm3SXHHZHmIlHQv2v0.jpg",
      "https://framerusercontent.com/images/NZZLsIWbC3cmjtBAq6ic0ZKtEGk.jpg",
      "https://framerusercontent.com/images/yiMUK0j8IUkxCC0ckfqqcY0viY.jpg",
      "https://framerusercontent.com/images/foR6SUCW2Ib3YMbAqtLw32NdzAY.jpg",
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
