export interface Project {
  slug: string;
  title: string;
  category: string;
  year: string;
  previewImage: string;
  buttonText: string;
  previewLink: string;
  overview: string;
  client: string;
  service: string;
  challengeTitle: string;
  challengeText: string;
  solutionTitle: string;
  solutionText: string;
  gallery: string[];
}

export const projects: Project[] = [
  {
    slug: "neon-flux",
    title: "Neon Flux",
    category: "Fashion Editorial",
    year: "'22",
    previewImage: "https://framerusercontent.com/images/DizHARMZJvhRrgRzoshkdmIiL28.jpg",
    buttonText: "Live project",
    previewLink: "thaer.shop",
    overview: "A high-concept editorial blending cyberpunk aesthetics with bold color lighting, created for an avant-garde fashion brand.",
    client: "Neon Flux Apparel",
    service: "Photography",
    challengeTitle: "Challenge",
    challengeText: "Capture a futuristic tone while keeping the collection's craftsmanship and textures visible under vibrant lighting.",
    solutionTitle: "Solution",
    solutionText: "Used a mix of neon gels, reflective surfaces, and low-key lighting setups to create a dynamic, otherworldly visual mood while highlighting fabric detail.",
    gallery: [
      "https://framerusercontent.com/images/YXqXVZ8oiZdT2LUIKKnsiHVZaXQ.jpg",
      "https://framerusercontent.com/images/0U1st2R4vX6hOJmWeDlwAOxledU.jpg",
      "https://framerusercontent.com/images/MQBYmeEKfAR5PvR5xvJLUJo8.jpg",
      "https://framerusercontent.com/images/nPNs6HN2OweGhXRLO3SK11JXwgA.jpg",
      "https://framerusercontent.com/images/H6naCCCwp3wMtmvjaX9wdG5yOXI.jpg",
    ],
  },
  {
    slug: "lumina-city",
    title: "Lumina City",
    category: "Conceptual Series",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/fH1YoRgLBMvw05yvsusCgLYGY.png",
    buttonText: "Live project",
    previewLink: "thaer.shop",
    overview: "A nighttime urban photography project exploring the intersection of architecture, light, and technology.",
    client: "Gallery Exhibition",
    service: "Photography",
    challengeTitle: "Challenge",
    challengeText: "Convey a sense of near-future city life without relying on heavy digital manipulation.",
    solutionTitle: "Solution",
    solutionText: "Leveraged long exposure techniques, LED installations, and precise framing to create cinematic, futuristic imagery straight out of camera.",
    gallery: [
      "https://framerusercontent.com/images/Pr4YBlH2I18xrIiYVSGIfWCDU.jpg",
      "https://framerusercontent.com/images/tNDsQjkK9a1W4ZlHHy6Q3bAVGHI.jpg",
      "https://framerusercontent.com/images/dSCQ0YO0t5XkW5AsGpr7VIJL3I.jpg",
      "https://framerusercontent.com/images/UAZltr2XP2JeEg1bGpysyUuCiE.jpg",
      "https://framerusercontent.com/images/kNXyPDtLG8v02FAGmr45easj98.jpg",
    ],
  },
  {
    slug: "kanso",
    title: "Kanso",
    category: "Design Agency",
    year: "'25",
    previewImage: "https://framerusercontent.com/images/0JqN0I0NxBZBY7Ro4fimcjlr0g.jpg",
    buttonText: "Live website",
    previewLink: "https://kanso.framer.media/",
    overview: "Kanso is a premium template for design agencies and creative studios that value clarity, precision, and timeless aesthetics.",
    client: "Framer template",
    service: "Web design",
    challengeTitle: "Features",
    challengeText: "It balances clean typography, structured layouts, and smooth animations to deliver a seamless user experience.",
    solutionTitle: "Scope",
    solutionText: "Whether you're presenting brand identities, digital products, or creative campaigns, Kanso provides the flexibility to let your work take center stage.",
    gallery: [
      "https://framerusercontent.com/images/uMFQ2z0nFgi8cj9lwtdIVrKcH3U.jpg",
      "https://framerusercontent.com/images/K6o9sUaC2WbrBFFNg6dLy2aJf8c.jpg",
      "https://framerusercontent.com/images/0I7SxunxLIshSwCrvVdGTufSqzk.jpg",
    ],
  },
  {
    slug: "eclat",
    title: "Éclat",
    category: "Brand Identity",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/RaSrkE8nM37bsXSaA4VshcSjg2c.jpg",
    buttonText: "Live project",
    previewLink: "thaer.shop",
    overview: "Complete visual identity design for a contemporary jewelry label, including logo, color palette, and brand guidelines.",
    client: "Éclat Jewelry",
    service: "Visual Identity",
    challengeTitle: "Challenge",
    challengeText: "The brand needed a visual identity that balanced luxury with a minimal, modern aesthetic to appeal to a younger demographic.",
    solutionTitle: "Solution",
    solutionText: "Designed a refined wordmark with subtle detailing, paired with a sophisticated yet contemporary palette and clean brand system.",
    gallery: [
      "https://framerusercontent.com/images/zBOcZQv01mdr4RGpBfYqh318Q.jpg",
      "https://framerusercontent.com/images/Bkgn6YRamshLbKA9cKIVgLFitw.jpg",
      "https://framerusercontent.com/images/QBQa3mIm3SXHHZHmIlHQv2v0.jpg",
      "https://framerusercontent.com/images/NZZLsIWbC3cmjtBAq6ic0ZKtEGk.jpg",
      "https://framerusercontent.com/images/yiMUK0j8IUkxCC0ckfqqcY0viY.jpg",
      "https://framerusercontent.com/images/foR6SUCW2Ib3YMbAqtLw32NdzAY.jpg",
    ],
  },
  {
    slug: "amber",
    title: "Amber",
    category: "Creative Studio",
    year: "'25",
    previewImage: "https://framerusercontent.com/images/rSYCc9NuZxZZzbjxPH3muXhXZvg.jpg",
    buttonText: "Live website",
    previewLink: "https://amber.framer.media/",
    overview: "Amber is a premium portfolio template for filmmakers, creative agencies, and photographers.",
    client: "Framer template",
    service: "Web design",
    challengeTitle: "Concept",
    challengeText: "Amber is a premium portfolio template for filmmakers, production studios, creative agencies, and photographers. With a minimal layout and refined typography, Amber showcases your work with clarity and impact.",
    solutionTitle: "Scope",
    solutionText: "Built with a minimal layout, refined typography, and a focus on visual storytelling, Amber creates a seamless canvas for your work to shine. Every detail is crafted to elevate your portfolio, ensuring your films, images, and projects leave a lasting impression.",
    gallery: [
      "https://framerusercontent.com/images/AaYLA1yhidzg7tDVCJPBFkbWU.jpg",
      "https://framerusercontent.com/images/YiPP5eVO00N0ZsYiybYqyphIk.jpg",
      "https://framerusercontent.com/images/3gJReDa5BpWEsSKGHwx3Ph0xc.jpg",
    ],
  },
  {
    slug: "cote-sauvage",
    title: "Côte Sauvage",
    category: "Travel Editorial",
    year: "'23",
    previewImage: "https://framerusercontent.com/images/CqkOPjD1SlEzLYIoZGMdGUT5w.jpg",
    buttonText: "Live project",
    previewLink: "thaer.shop",
    overview: "A visual story capturing the raw beauty of France's Atlantic coast, shot for a lifestyle magazine feature.",
    client: "Côte Sauvage Magazine",
    service: "Photography",
    challengeTitle: "Challenge",
    challengeText: "Weather conditions were unpredictable, making it difficult to plan for consistent light and atmosphere.",
    solutionTitle: "Solution",
    solutionText: "Adapted the shoot schedule to chase optimal light, embracing dramatic skies and moody tones to enhance the editorial narrative.",
    gallery: [
      "https://framerusercontent.com/images/wCkQr2zDR08Vy6xX8mS1lsvZE.jpg",
      "https://framerusercontent.com/images/XPFByP9h7E7xgKp3aHf0zuyxzQ.jpg",
      "https://framerusercontent.com/images/uDETrNAAbgCzHqNUpnzGNAiyP4.jpg",
      "https://framerusercontent.com/images/5IOKMsZGqZH5baVORJfb94L6KM4.jpg",
    ],
  },
  {
    slug: "calisto",
    title: "Calisto",
    category: "AI Agency Website",
    year: "'25",
    previewImage: "https://framerusercontent.com/images/jcmBjluMDrVi5NXW9ZtGVQOrJpI.jpg",
    buttonText: "Live website",
    previewLink: "https://calisto.framer.website/",
    overview: "Calisto is a modern Framer template built for AI automation agencies and startups.",
    client: "Framer template",
    service: "Web design",
    challengeTitle: "Concept",
    challengeText: "With elegant layouts and seamless animations, it's designed to showcase your services with clarity and impact, helping you build trust and convert leads effortlessly.",
    solutionTitle: "Features",
    solutionText: "Calisto combines clean design with purposeful structure to help you present your brand, services, and results with confidence.",
    gallery: [
      "https://framerusercontent.com/images/axJGoIx7xyzBOE4ZzKU31lZYJsE.jpg",
      "https://framerusercontent.com/images/GV0tzcN1ITMr4gDpFvVDvLKwNqY.jpg",
      "https://framerusercontent.com/images/uumOeVdewZj5oX4u69tpJS6EQ.jpg",
    ],
  },
  {
    slug: "atelier",
    title: "Atelier",
    category: "Brand Photography",
    year: "'23",
    previewImage: "https://framerusercontent.com/images/KwOIBd14OUFE2m4G8YX20blRVE.jpg",
    buttonText: "Live preview",
    previewLink: "thaer.shop",
    overview: "A minimalist editorial photoshoot highlighting handcrafted ceramics in natural light for use across print and digital.",
    client: "Atelier Lumière",
    service: "Photography",
    challengeTitle: "Challenge",
    challengeText: "The brand wanted imagery that conveyed the artisanal nature of their ceramics while keeping the tone modern and timeless.",
    solutionTitle: "Solution",
    solutionText: "Used diffused natural light and neutral backgrounds to emphasize texture and craftsmanship, creating a series of clean, cohesive images.",
    gallery: [
      "https://framerusercontent.com/images/jVqCkEkTcLzubjAcnZqxgrMzgs.jpg",
      "https://framerusercontent.com/images/EZ6FyXr46GicQeSvRsAWhf9kRWg.jpg",
      "https://framerusercontent.com/images/pbL0mUDwLh1Y4SW7OSYQiGZiVqk.jpg",
      "https://framerusercontent.com/images/zACxCnLqLw2YFiC2M3CyuUYm7hI.jpg",
    ],
  },
  {
    slug: "scarlet",
    title: "Scarlet",
    category: "Design Agency",
    year: "'25",
    previewImage: "https://framerusercontent.com/images/f7oyi2aIDMI2iUNKjywMMhvxJw.jpg",
    buttonText: "Live website",
    previewLink: "https://scarlet.framer.media/",
    overview: "Scarlet is a modern template for design agencies, creative studios, and personal portfolios.",
    client: "Framer template",
    service: "Web design",
    challengeTitle: "Concept",
    challengeText: "Scarlet is a modern template for design agencies, creative studios, and personal portfolios. It offers a seamless user experience with bold typography, smooth animations, and a clean layout.",
    solutionTitle: "Scope",
    solutionText: "With a perfect balance of minimalism and sophistication, it provides a stunning visual framework to showcase your visual and video projects, engage potential clients, and establish a strong online presence.",
    gallery: [
      "https://framerusercontent.com/images/0YXh0bkFGKxtQXqwZ4FknVxQ.jpg",
      "https://framerusercontent.com/images/vRcX31A0p0E7RIv4uPKIu2atBg.jpg",
      "https://framerusercontent.com/images/gqLJuWPk1O9hiVXDLjNdgetfJo4.jpg",
    ],
  },
  {
    slug: "cafe-nord",
    title: "Café Nord",
    category: "Rebrand",
    year: "'24",
    previewImage: "https://framerusercontent.com/images/vbCFzEQhFbjMnzTyy0HJBzCwlIY.jpg",
    buttonText: "Live project",
    previewLink: "thaer.shop",
    overview: "Development of a modern, Scandinavian-inspired identity for a boutique café, extending into menus, packaging, and signage.",
    client: "Café Nord",
    service: "Visual Identity, Graphic Design",
    challengeTitle: "Challenge",
    challengeText: "The café wanted a Scandinavian feel without looking generic or overly minimal.",
    solutionTitle: "Solution",
    solutionText: "Combined clean typography with warm accent colors and subtle texture elements, creating a brand that feels both modern and inviting.",
    gallery: [
      "https://framerusercontent.com/images/X3PjTLiK3d1YoVxfiOwUhlGvx8.jpg",
      "https://framerusercontent.com/images/Kfc7YrMQRL7DaiQuGMSGwB2dIk.jpg",
      "https://framerusercontent.com/images/8K7i1HVZKZeTqqK56wJIvLHCFh0.jpg",
      "https://framerusercontent.com/images/qOI5dXCoWkxXMyJ3q0eR5OoF7dw.jpg",
    ],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
